### ISSUE TITLE
IceFrog Issues Summary

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#205]
- [x] use **Nicks Module** for validators nick name #176, fixed in #218
- [x] `bond` zero should failed, fixed in #218
- [x] replace the Alice, Bob in `initial_accounts` with custom accounts #240, fixed in #241
- [x] how to clean staking system #154, fixed in #249 
- [x] the account from `parse_proof` need to be existed to `redeem`, bug or design?
- [x] binary built from different machine can't connect, fixed in #210
- [x] storage root must match that calculated #213 
- [ ] duplicate header relay shoud fail, but didn't #214
- [x] unexpected new session/era #216
- [x] `BondDuration` mismatched #221, fixed in #218
- [x] slash base on `Exposure` #222, fixed in #218 
- [x] finalized block stuck #230
- [x] promise month Less than 3 should be 0 in BondRing event #234, fixed in #218
- [x] `CurrencyToVote` to `PowerToVote` #238, fixed in #218 
- [x] should be `ForceNew` #242, fix in #257
- [x] unexpected epoch change when all nodes down #245

**Comment by HackFisher** [comment]
#214 is require to fix before next Crab testnet, close this for now.
