### ISSUE TITLE
Darwinia v0.10.0 Release Checklist

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#651]
## Runtime
- [x] `spec_version`
- [x] `transaction_version`

## Substrate Updates
- [x] #626
- [x] #619
 
## Infrastructure
- [x] Apps cc @WoeOm 
- [x] Bridger cc @wuminzhe 

## Try Runtime
- [x] Crab
	```
	2021-04-22 17:30:53 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0
	2021-04-22 17:30:53 [#0] 🗳  Finalized election round with compute ElectionCompute::OnChain.
	2021-04-22 17:30:53 [0] 💸 new validator set of size 1 has been processed for era 1
	2021-04-22 17:30:53 initializing remote client to "http://127.0.0.1:20009"
	2021-04-22 17:30:53 scraping keypairs from remote node http://127.0.0.1:20009 @ 0x3d786690f4aee5d6f72fa4e36d46219ce8ab9d0418d9805a164cc09be1dd36bb
	2021-04-22 17:30:53 downloading data for all modules.
	2021-04-22 17:38:56 extending externalities with 1 manually injected keys
	2021-04-22 17:38:56 injecting a total of 11188481 keys
	2021-04-22 17:42:40 try-runtime::on_runtime_upgrade Darwinia.
	2021-04-22 17:42:40 [4930178] 💸 SnapshotValidators.exits()? false
	2021-04-22 17:42:40 [4930178] 💸 SnapshotNominators.exits()? false
	2021-04-22 17:42:40 [4930178] 💸 QueuedElected.exits()? false
	2021-04-22 17:42:40 [4930178] 💸 QueuedScore.exits()? false
	2021-04-22 17:42:40 ⚠️ System declares internal migrations (which *might* execute), setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for TronBacking, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for EthereumRelayAuthorities, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for EthereumRelayerGame, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for EthereumBacking, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for EthereumRelay, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for CrabBacking, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Multisig, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Proxy, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Scheduler, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Recovery, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Society, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Identity, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Utility, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Vesting, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Sudo, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Treasury, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for TechnicalMembership, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for ElectionsPhragmen, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for TechnicalCommittee, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Council, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Democracy, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for HeaderMMR, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for AuthorityDiscovery, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for ImOnline, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Grandpa, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Session, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Historical, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Offences, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ⚠️ Staking declares internal migrations (which *might* execute), setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 [4930178] 💸 Migrating staking to Releases::V6_0_0
	2021-04-22 17:42:40 [4930178] 💸 Done.
	2021-04-22 17:42:40 ✅ no migration for ElectionProviderMultiPhase, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Authorship, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for TransactionPayment, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Kton, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Balances, setting storage version to PalletVersion { major: 2, minor: 2, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Timestamp, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for Babe, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 ✅ no migration for RandomnessCollectiveFlip, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }
	2021-04-22 17:42:40 try-runtime executed without errors. Consumed weight = 1025152000000000, total weight = 512000000000000 (2.00225)
	```
- [x] Darwinia

## Running Local Network for At Least 12 Hours
- [x] Crab
- [x] Darwinia

## Checking
- Crab
	- [x]  Verify previously completed migrations are removed for any public (non-private/test) networks.
	- [x] Verify new migrations complete successfully, and the runtime state is correctly updated for any public (non-private/test) networks.
	- [x] Verify Apps are up to date with the latest runtime changes.
	- [x] Check the DVM-Crab can connect with metamask and transfer.
	- [x] Check the DVM-Crab works well with contract deployment and other cases.
- Darwinia
	- [x]  Verify previously completed migrations are removed for any public (non-private/test) networks.
	- [x] Verify new migrations complete successfully, and the runtime state is correctly updated for any public (non-private/test) networks.
	- [x] Verify Apps are up to date with the latest runtime changes.

**Comment by HackFisher** [comment]
- [ ] #619
