### ISSUE TITLE
Darwinia <> Ethereum Bridge Upgrade CheckList

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#714]
- [x] Introduce the message layer for Darwinia <> Ethereum. The message inbound and outbound channel. `LockAssetEvents` in Backing Module should be refactored to represent as messages in Darwinia Message Outbound Channel. cc @hujw77 @AurevoirXavier .
  + [x] https://github.com/darwinia-network/darwinia-common/issues/627 and Backing & Issuing might be better to move to (wormhole)token protocol related folders.
  + [x] Ethereum smart contracts for message layer. https://github.com/darwinia-network/darwinia-bridge-sol/issues/76 cc @hujw77 
- [ ] Replace MMR pallet with parity's https://github.com/darwinia-network/darwinia-common/pull/743 and support pruning(for sure), and update the MMR Leaf spec https://github.com/darwinia-network/darwinia-common/issues/665 cc @AurevoirXavier @hujw77 
  + [ ] message root part in mmr leaf also related to the optimization of gas fee in Ethereum part
  + [ ] BEEFY integration https://github.com/paritytech/substrate/pull/9833, https://github.com/darwinia-network/darwinia-common/pull/746 @AurevoirXavier 
  + [ ] Custom [commitment](https://github.com/darwinia-network/darwinia-bridge-sol/blob/09d35a38264fc6dd38d95761ecb129cf8c31b5f6/contracts/bridge/contracts/common/spec/BeefyCommitmentScheme.sol#L42) and [MessageRoot](https://github.com/darwinia-network/darwinia-bridge-sol/blob/09d35a38264fc6dd38d95761ecb129cf8c31b5f6/contracts/bridge/contracts/darwinia/message/ChainMessageCommitter.sol#L29) in BEEFY @AurevoirXavier  
- [x] Adding truth layer in Darwinia > Ethereum by introducing Beefy https://github.com/darwinia-network/darwinia-common/pull/746 @hujw77 @AurevoirXavier 
  + [x] Ethereum smart contracts for Beefy and Grandpa light client. cc @hujw77 
  + [x] https://github.com/darwinia-network/darwinia-common/issues/755
- [x] Adding truth layer in BSC > Darwinia @hujw77 @xiaoch05 
  + [x] BSC light client pallet
  + [x] BSC light client lane_data https://github.com/darwinia-network/darwinia-common/pull/988 @xiaoch05 
- [x] Backing and Issuing upgrade
  + [x] Use new message layer and truth layer(light client) https://github.com/darwinia-network/darwinia-bridge-sol/pull/101 cc @xiaoch05 , 
  + [x] Solidity upgrade, remove permission from old contract, and use new contract.
- [x] Basic Relayer Incentive Support: Relayer Fee Market cc @xiaoch05 @hujw77 
- [x] Companion Bridger Upgrade cc @furoxr 
   + [ ] [Interact](https://www.notion.so/itering/BEEFY-Commitment-7f705fe6dade482d8119a10b441d1bb1) with [BEEFY](https://www.notion.so/itering/GRANDPA-BEEFY-Light-Client-7574040688064c098b931ca4ebee5369) protocol, (Darwinia header relay) 
   + [ ] [Interact](https://github.com/darwinia-network/darwinia-common/blob/master/frame/bridge/bsc/src/lib.rs) with BSC light client pallet (BSC header relay)
   + [ ] [Message relay](https://www.notion.so/itering/Message-Protocol-V2-c41f0c9e453c478abb68e93f6a067c52)
   + [ ] Interact with fee market  
- [x] Companion wormhole Upgrade cc @1022ranji @sxlwar

**Comment by HackFisher** [comment]
- [ ] Will relayer help user to deliver the message to Ethereum, originally require use to claim by themself.
- [ ] Support of deprecated tokens claiming in previous Darwinia > Ethereum bridge.

**Comment by AurevoirXavier** [comment]
Please update this.

cc @AsceticBear @HackFisher @xiaoch05

**Comment by HackFisher** [comment]
eth2 : https://github.com/darwinia-network/darwinia-messages-sol/pull/166
