### ISSUE TITLE
substrate<>substarte bridge checklist

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/darwinia#720]
The first stage goal is to support the native token RING/KTON transfer from Darwinia Network to Crab DVM.
+ Test network support s2s bridge, we already have Pangolin network, need another chain called Pangoro
  + [x] Pangolin test for Crab (have EVM environment)
  + [x] Pangoro test for Darwinia (have no EVM environment) https://github.com/darwinia-network/darwinia-common/pull/773 @AurevoirXavier @wi1dcard 
+ Bridger
  + [x] New bridge support s2s（new types update） @fewensa  https://github.com/darwinia-network/bridger/pull/255
  + [x] Common files in parity bridge crate migration. https://github.com/paritytech/parity-bridges-common/pull/1082 @fewensa 
  + [x] decrease relayer's gas used. https://github.com/paritytech/parity-bridges-common/pull/975 (test and check if solved @xiaoch05 )
  + [x] can relayer is not sudo account? @fewensa https://github.com/darwinia-network/bridger/commit/67cd512f68fe781cbf9a8ef1ae7e18605490d507  https://sourcegraph.com/github.com/paritytech/parity-bridges-common@0b18f59/-/blob/modules/grandpa/src/lib.rs?L184-202
  + [x] check if need to upgrade parity-bridge-common pkg @xiaoch05 
+ Wormhole
  + [x] list s2s requirements. @xiaoch05 
  + [x] subquery listen and record s2s event in pallets @sxlwar 
  + [x] theGraph listen and record s2s event in contract @xiaoch05 @freehere107 
  + [x] the mapped asset's name @HackFisher @xiaoch05  https://github.com/darwinia-network/darwinia-bridge-sol/blob/master/docs/Wormhole%20Mapping%20Token%20Metadata%20Standards.md
  + [x] UI @sxlwar  
+ The standard of message protol
  + Currently we do nothing for this. Waiting for XCM and parity bridge message unify
+ security
  + [x] the panic bug https://github.com/darwinia-network/darwinia/issues/703 need to submit a change request to parity-bridge @AurevoirXavier @xiaoch05 
  + [x] limit daily transfer amount and confirm deliver message @xiaoch05 
  + [ ] code review @darwinia-network
  + [ ] more test @darwinia-network
- [x]  Folder structure and rename https://github.com/darwinia-network/darwinia-common/issues/627 @AurevoirXavier 
- Fee system, currently we use parity-bridge-common's fee feature. Later change it to ourselves.

**Comment by wi1dcard** [comment]
Just a reminder - mention ALL doesn't mean all members in the GitHub organization. Instead, it's just a person with the id "all".

**Comment by xiaoch05** [comment]
Test on Pangolin<>Pangoro testnet, the bridge's configure is as follows
```
[pangolin]
endpoint = "wss://pangolin-rpc.darwinia.network"
signer = "//Alice"

[pangoro]
endpoint = "wss://pangoro-rpc.darwinia.network"
signer = "//Alice"

[relay]
lanes = ["72746c6c"]
auto_start = true
signer_pangolin = "//Alice"
signer_pangoro = "//Alice"

[relay.prometheus_params]
no_prometheus = false
prometheus_host = "127.0.0.1"
prometheus_port = 9616
```
