### ISSUE TITLE
Substrate Update Problem Tracking

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#83]
### Substrate Update Problem Tracking

Now, we're making an update with [substrate#65345696](https://github.com/paritytech/substrate#65345696).

### Problems:

- ~~compiling failed with latest rust toolchain~~
	- [x] PR: #82
	- [x] ~~again, we need to stay at `rustup default nightly-2019-10-13` for *nightly features*~~
	- [x] tracking: https://github.com/rust-lang/rust/issues/65462
- ~~number of keys in session handler and session keys does not match~~
	- [x] PR: #92 
	- [x] tracking: https://github.com/darwinia-network/darwinia/issues/98

**Comment by hammeWang** [comment]
Have you encountered any problems? @AurevoirXavier

**Comment by AurevoirXavier** [comment]
Have no other problems at the moment.

**Comment by hammeWang** [comment]
@AurevoirXavier closed for now. you could open new issues with more specific errors or thinkings.
We may add labels to keep tracking the newly coming-up challenges.

**Comment by HackFisher** [comment]
```
rustup install nightly-2019-10-13
rustup default nightly-2019-10-13
rustup target add wasm32-unknown-unknown --toolchain=nightly-2019-10-13
```
