### ISSUE TITLE
Crab Parachain <> Crab Chain Bridge Checklist

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#835]
![image](https://user-images.githubusercontent.com/1070122/155689921-3564871e-9a1a-4c95-a915-3f6e1712a26c.png)

As the above diagram indicates, to support the bridge between Crab parachain and Crab chain, the bridge can be separated to following part:

- Truth Layer(Header Finality):
  - On-chain pallets  cc @AurevoirXavier @furoxr   :
    - [x] Deploy pallet-bridge-grandpa for Kusama(as source parachain's relay chain) on target chain Crab
    - [x] Deploy pallet-bridge-parachains for Crab parachain (via Kusama) on target chain Crab Ref: https://github.com/paritytech/parity-bridges-common/pull/1068
    - [x] Deploy pallet-bridge-grandpa for Crab(as source chain ) on target chain Crab parachain
  - Relayer client(Bridger, cc @fewensa @furoxr )
    - [x] Grandpa finality header relay for Kusama to Crab and Crab to Crab parachain
    - [x] Parachain header relay for Crab parachain to Crab for pallet-bridge-parachains, using parachain header proof via Kusama Ref: https://github.com/paritytech/parity-bridges-common/pull/1199
    - [x] Integration Test
  
- Message Layer:
  - [x] Deploy pallet-bridge-message pallets for Crab parachain and Crab chain. cc @AurevoirXavier 
  - [x] Parachain message relay(bridger).  https://github.com/darwinia-network/bridger/issues/416 and https://github.com/paritytech/parity-bridges-common/pull/1218
  - [x] Relayer Fee market.
  - [x] Integration Test

- Token Layer for Crab Token(Wormhole cc @xiaoch05 @1022ranji)
  - [ ] Backing pallet on Crab chain
  - [ ] Issuing pallet on Crab parachain
  - [ ] User interface
  - [ ] Integration Test
