### ISSUE TITLE
Benchmark updates

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#986]
I hope we can have this update.

https://github.com/paritytech/substrate/pull/12924

Then, we can start the:
- [x] darwinia-network/darwinia-2.0#95 
- [x] darwinia-network/darwinia#971 
- [x] darwinia-network/darwinia#975 
- [x] #1030
